EXCHANGE_API_URL = "https://www.koreaexim.go.kr/site/program/financial/exchangeJSON"
PARAM_PATH = r"./param.json"

DATA_PARAM = 'AP01' # exchage

RESULT_PARAM_SUCESS = 1
RESULT_PARAM_DATA_CODE_ERROR = 2
RESULT_PARAM_AUTH_CODE_ERROR = 3
RESULT_PARAM_DAILY_LIMIT_NOTIFICATION = 4